version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxi
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

  loader:
    build: ./loader
    environment:
      - DATABASE_URL=postgresql://user:postgres@db:5432/taxi
      - CSV_PATH=/data/yellow_tripdata_2021-01.csv.gz
    volumes:
      - ./data:/data
    depends_on:
      - db
